services:

  postgres:
    build: docker_database
    environment:
      POSTGRES_DB: "maindb"
      POSTGRES_USER: "main_user"
      POSTGRES_PASSWORD: "admin"
    
    ports:
      - "30042:5432"

    volumes:
      - ./postgres-data:/var/lib/postgresql/data

    networks:
      - postgres

    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container

    ports:
      - "5050"

    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@jeeeez.com
      PGADMIN_DEFAULT_PASSWORD: admin

    networks:
      - postgres

    volumes:
      - ./pgadmin-data:/var/lib/pgadmin

    restart: unless-stopped

networks:
  postgres:
    driver: bridge
